package web.app.sample.main;

/*Generated by MPS */

import jetbrains.springframework.configuration.runtime.ServiceLocatorAdapter;

public class InitWebApplicationServiceLocatorListener extends ServiceLocatorAdapter {
  public void onAfterInit() {
  }
}
