package web.app.sample.main;

/*Generated by MPS */

import jetbrains.mps.webr.runtime.templateComponent.ITemplateFactory;
import jetbrains.mps.webr.runtime.templateComponent.TemplateComponent;
import java.util.Map;

public class MessageBoard_RootHtmlTemplateFactory implements ITemplateFactory {
  public MessageBoard_RootHtmlTemplateFactory() {
  }

  public TemplateComponent create() {
    return new MessageBoard_RootHtmlTemplateComponent();
  }

  public TemplateComponent create(TemplateComponent parent, String name, Map<String, Object> params) {
    return new MessageBoard_RootHtmlTemplateComponent(parent, name, params);
  }
}
