package web.app.sample.main;

/*Generated by MPS */

import jetbrains.mps.webr.runtime.templateComponent.RootTemplateController;
import jetbrains.mps.webr.runtime.templateComponent.ActionController;
import jetbrains.mps.webr.runtime.templateComponent.IdParameter;
import jetbrains.mps.webr.runtime.templateComponent.TemplateActionController;
import jetbrains.mps.webr.runtime.templateComponent.ActionFactory;
import jetbrains.mps.webr.runtime.templateComponent.TemplateComponent;
import webr.framework.textBuilder.TBuilderContext;

public class MessageBoard_RootHtmlTemplateController extends RootTemplateController {
  public MessageBoard_RootHtmlTemplateController() {
    super("MessageBoard");
  }

  public ActionController createAction(String idParameterValue, String windowId) {
    IdParameter idParameter = null;
    return new MessageBoard_RootHtmlTemplateController.Action(windowId, this, idParameter, true);
  }

  private static class Action extends TemplateActionController {
    public Action(String windowId, ActionFactory actionFactory, IdParameter idParameter, boolean transactional) {
      super("MessageBoard", windowId, actionFactory, transactional);
      this.setIdParameter(idParameter);
    }

    public TemplateComponent createTemplateComponent(TBuilderContext builderContext) {
      String rootTemplateName = "MessageBoard";
      rootTemplateName = StringUtils.substring(rootTemplateName, 0, 1).toUpperCase();
      builderContext.setCurrentTemplateName(rootTemplateName);
      TemplateComponent templateComponent = new MessageBoard_RootHtmlTemplateComponent(this, rootTemplateName, null);
      templateComponent.setRefName(rootTemplateName);
      builderContext.pushCurrentTemplateComponent(templateComponent);
      builderContext.popCurrentTemplateComponent();
      return templateComponent;
    }
  }
}
