package web.app.sample.sandbox.persistence;

/*Generated by MPS */

import com.jetbrains.teamsys.dnq.database.BasePersistentClassImpl;
import jetbrains.teamsys.dnq.runtime.util.DnqUtils;
import jetbrains.exodus.entitystore.Entity;
import com.jetbrains.teamsys.dnq.association.PrimitiveAssociationSemantics;

public class UserImpl extends BasePersistentClassImpl {
  private static String __ENTITY_TYPE__ = "User";

  public UserImpl() {
  }

  public void run() {
    DnqUtils.setPersistentClassInstance(__ENTITY_TYPE__, this);
  }

  protected Entity _constructor(String username, final String _entityType_) {
    final Entity entity;
    entity = super._constructor(_entityType_);
    PrimitiveAssociationSemantics.set(entity, "name", username, String.class);
    return entity;
  }

  public static Entity constructor(String username) {
    return ((UserImpl) DnqUtils.getPersistentClassInstance(null, __ENTITY_TYPE__))._constructor(username, __ENTITY_TYPE__);
  }
}
